version: '3.9'

services:
  split-eats-api:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
  split-eats-fe:
    build: ./frontend
    ports:
      - "8001:80"
    restart: unless-stopped
