[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-cors = {version =  "0.7.0" }
actix-web = { version = "4.9.0" }
serde = { version = "1.0.215", features = ["derive"] }
uuid = {version =  "1.11.0", features = ["v4"] }
